name: CI
on:
  pull_request:
  push:
    branches: ['**']
    tags: [v*]
permissions:
  contents: write        # release-drafter, auto-merge requirement
  pull-requests: write   # labeler, auto-merge requirement    
env:
  # .sbtopts specifies 8g, which is needed to import into IntelliJ, but on GH that exceeds the maximum available memory
  SBT_JAVA_OPTS: -J-Xms4g -J-Xmx4g
jobs:
  ci:
    # run on 1) push, 2) external PRs, 3) github-actions PRs
    # do not run on internal, non-steward PRs since those will be run by push to branch
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.full_name != github.repository ||
      github.event.pull_request.user.login == 'softwaremill-ci'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        scala-version: [ "2.12", "2.13", "3" ]
        target-platform: [ "JVM", "JS", "Native" ]
        java: [ "11", "21" ]
        exclude:
          - java: "21"
        include: # Restricted to build only specific Loom-based modules
          - scala-version: "2.13"
            target-platform: "JVM"
            java: "21"
          - scala-version: "3"
            target-platform: "JVM"
            java: "21"
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - uses: sbt/setup-sbt@a627500d27445f8c5021755a439829b6e78e3358 # v1, specifically v1.1.15
    - name: Set up JDK 
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        cache: 'sbt'
        java-version: ${{ matrix.java }}
    - name: Install sam cli
      if: matrix.java == '11'
      run: |
        wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
        sudo ./sam-installation/install --update
        sam --version
    - name: Install NPM
      if: matrix.java == '11'
      uses: actions/setup-node@v6
      with:
        node-version: 18
    - run: npm --version
    - name: Install AWS CDK
      if: matrix.java == '11'
      run: |
        npm install -g aws-cdk
        cdk --version
    - name: Install libidn2-dev libcurl3-dev
      if: matrix.target-platform == 'Native'
      run: |
        sudo apt-get update
        sudo apt-get install libidn2-dev libcurl3-dev
        echo "STTP_NATIVE=1" >> $GITHUB_ENV
    - name: Install scala-cli
      if: matrix.target-platform == 'JVM' && matrix.java == '21' && matrix.scala-version == '3'
      uses: VirtusLab/scala-cli-setup@89a48599f871d08573707e82bdcefbce839de436 # main, specifically v1.11.0
      with:
        jvm: '' # needed because scala-cli-setup otherwise forces the installation of their default JVM (17)
    - name: Enable Loom-specific modules
      if: matrix.java == '21'
      run: echo "ONLY_LOOM=1" >> $GITHUB_ENV
    - name: Compile
      run: sbt $SBT_JAVA_OPTS -v "compileScoped ${{ matrix.scala-version }} ${{ matrix.target-platform }}"
    - name: Compile documentation
      if: matrix.target-platform == 'JVM' && matrix.java == '21'
      run: sbt $SBT_JAVA_OPTS -v compileDocumentation
    - name: Verify that examples compile using Scala CLI
      if: matrix.target-platform == 'JVM' && matrix.java == '21' && matrix.scala-version == '3'
      run: sbt $SBT_JAVA_OPTS -v "project examples3" verifyExamplesCompileUsingScalaCli
    - name: Test
      if: matrix.target-platform != 'JS'
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3, specifically v3.0.2
      with:
        timeout_minutes: 10
        max_attempts: 2
        # the netty server interpreter tests include some which run a large number of requests, to detect potential leaks
        # storing the output to verify it in the next step
        command: |
          sbt $SBT_JAVA_OPTS -v "testScoped ${{ matrix.scala-version }} ${{ matrix.target-platform }}" 2>&1 | tee output.log
          exit ${PIPESTATUS[0]}
    - name: Check for reported leaks
      if: matrix.target-platform != 'JS'
      run: |
          if grep -q "LEAK" output.log; then
            echo "Leak detected!"
            exit 1
          fi
    - name: Test OpenAPI codegen
      if: matrix.target-platform == 'JVM' && matrix.scala-version == '2.12'
      run: sbt $SBT_JAVA_OPTS -v "openapiCodegenSbt2_12/scripted"                
    # The finatra tests take a really long time (1/3 of the build duration); hence, they are disabled and need to be run separately
    #- name: Test finatra
    #  if: matrix.target-platform != 'JS'
    #  run: sbt $SBT_JAVA_OPTS -v testFinatra
    # Temporarily call JS tests for each subproject explicitly as a workaround until
    # https://github.com/scala-js/scala-js/issues/4317 has a solution
    - name: Test
      if: matrix.target-platform == 'JS' && matrix.scala-version == '2.12'
      run: sbt $SBT_JAVA_OPTS catsJS2_12/test circeJsonJS2_12/test clientCoreJS2_12/test clientTestsJS2_12/test coreJS2_12/test enumeratumJS2_12/test jsoniterScalaJS2_12/test newtypeJS2_12/test openapiDocsJS2_12/test playJsonJS2_12/test redocJS2_12/test serverCoreJS2_12/test sttpClientJS2_12/test testingJS2_12/test testsJS2_12/test uPickleJsonJS2_12/test zioJsonJS2_12/test
    - name: Test
      if: matrix.target-platform == 'JS' && matrix.scala-version == '2.13'
      run: sbt $SBT_JAVA_OPTS catsJS/test circeJsonJS/test clientCoreJS/test clientTestsJS/test coreJS/test enumeratumJS/test jsoniterScalaJS/test newtypeJS/test openapiDocsJS/test playJsonJS/test redocJS/test serverCoreJS/test sttpClientJS/test testingJS/test testsJS/test uPickleJsonJS/test zioJsonJS/test
    - name: Test
      if: matrix.target-platform == 'JS' && matrix.scala-version == '3'
      run: sbt $SBT_JAVA_OPTS catsJS3/test circeJsonJS3/test clientCoreJS3/test clientTestsJS3/test coreJS3/test jsoniterScalaJS3/test openapiDocsJS3/test redocJS3/test serverCoreJS3/test sttpClientJS3/test testingJS3/test testsJS3/test uPickleJsonJS3/test zioJsonJS3/test
    - uses: actions/upload-artifact@v6  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: 'tests-results-${{ matrix.scala-version }}-${{ matrix.target-platform }}-${{ matrix.java }}'
        path: '**/test-reports/TEST*.xml'
    - name: Prepare release notes
      uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6, specifically v6.1.0
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # identify binary incompatibilities (check build.sbt for details)
  mima:
    uses: softwaremill/github-actions-workflows/.github/workflows/mima.yml@main
    with:
      java-version: '21'
      java-opts: '-Xms4g -Xmx4g' # SBT_JAVA_OPTS env parameter adapted for JVM

  publish:
    name: Publish release
    needs: [ci]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        java: [ "11", "21" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: sbt/setup-sbt@a627500d27445f8c5021755a439829b6e78e3358 # v1, specifically v1.1.15
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'
      - name: Install libidn2-dev libcurl3-dev
        if: matrix.java == '11'
        run: |
          sudo apt-get update
          sudo apt-get install libidn2-dev libcurl3-dev
      - name: Enable Native-specific modules
        if: matrix.java == '11'
        run: echo "STTP_NATIVE=1" >> $GITHUB_ENV
      - name: Enable Loom-specific modules
        if: matrix.java == '21'
        run: echo "ONLY_LOOM=1" >> $GITHUB_ENV
      - name: Compile
        run: sbt $SBT_JAVA_OPTS compile
      - name: Publish artifacts
        run: sbt $SBT_JAVA_OPTS ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - name: Extract version from commit message
        if: matrix.java == '11'
        run: |
          version=${GITHUB_REF/refs\/tags\/v/}
          echo "VERSION=$version" >> $GITHUB_ENV
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
      - name: Publish release notes
        if: matrix.java == '11'
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6, specifically v6.1.0
        with:
          config-name: release-drafter.yml
          publish: true
          name: "v${{ env.VERSION }}"
          tag: "v${{ env.VERSION }}"
          version: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label:
    # only for PRs by softwaremill-ci
    if: github.event.pull_request.user.login == 'softwaremill-ci'
    uses: softwaremill/github-actions-workflows/.github/workflows/label.yml@main
    secrets: inherit

  auto-merge-github-actions:
    # only for PRs by softwaremill-ci
    if: github.event.pull_request.user.login == 'softwaremill-ci'
    needs: [ ci, mima, label ]
    uses: softwaremill/github-actions-workflows/.github/workflows/auto-merge.yml@main
    secrets: inherit

  auto-merge-dependabot:
    # only for PRs by dependabot[bot]
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    needs: [ ci, mima ]
    uses: softwaremill/github-actions-workflows/.github/workflows/auto-merge.yml@main
    secrets: inherit