# https://scala-lang.org/blog/2022/07/18/secure-your-dependencies-on-github.html
name: Update Dependency Graph

on:
  push:
    branches:
      - master

permissions:
  contents: write # needed to submit the dependency graph

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: sbt/setup-sbt@a627500d27445f8c5021755a439829b6e78e3358 # v1, specifically v1.1.15
      - uses: scalacenter/sbt-dependency-submission@49ca55b87774ad27542a25e20b4ecd2072985401 # v3, specifically v3.1.1
