# https://scala-lang.org/blog/2022/07/18/secure-your-dependencies-on-github.html
name: Update Dependency Graph

on:
  push:
    branches:
      - master

permissions:
  contents: write # needed to submit the dependency graph

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: sbt/setup-sbt@3e125ece5c3e5248e18da9ed8d2cce3d335ec8dd # v1, specifically v1.1.14
      - uses: scalacenter/sbt-dependency-submission@6567599b8237b6d2621b191a2a5181ccd28e1fab # v3, specifically v3.1.1
